### ISSUE TITLE
显示已完成,但是文件夹没有生成内容

### ISSUE THREAD

**Issue by yukminnie** [buxuku/video-subtitle-master#1]
系统: m1  sonoma 14.5
软件版本: 最新版
模型: large-v3
视频语言: 中文

---

其它: 

1, 执行过程有长时间处理器和内存占用, 并有音频文件生成
2, 界面提示执行成功后, 音频文件消失, 没有看到其它文件生成

**Comment by yukminnie** [comment]
更新:
1,  模型选择Medium, 我选择了"单独保存源字幕文件"的选项, 并且翻译服务, 我选择的是不翻译
2, 最后会输出翻译字幕, 但是源语言字幕依旧没有生成

**Comment by yukminnie** [comment]
然后, 反馈一个功能改进:

就是这个执行按钮, 建议设置点击后变色或者短时间不可再次点击, 第一次运行时以为没点到, 多点了一下, 然后系统挂了.😭

**Comment by buxuku** [comment]
非常感谢您的反馈建议，在不生成翻译字幕的选择情况下，这儿确实存在了一个逻辑判断的错误。另外我也增加了任务执行时的 loading 效果，防止重复点击。欢迎下载 1.0.1 版本尝试。
