### ISSUE TITLE
生成的字幕为啥都是英文？

### ISSUE THREAD

**Issue by Deepsea-pineapple** [buxuku/video-subtitle-master#10]
之前找错项目留言了，我是直接用这个应用程序，上传的视频讲的是中文，但给我翻译并生成英文字幕了

**Comment by buxuku** [comment]
whisper 默认识别语言是英文，程序里面之前确实没有向 whisper 指定识别语言，感谢反馈。当前 1.0.11 版本已经修复。

**Comment by Deepsea-pineapple** [comment]
> whisper 默认识别语言是英文，程序里面之前确实没有向 whisper 指定识别语言，感谢反馈。当前 1.0.11 版本已经修复。

好的，谢谢，另外再提两点建议，一是支持将视频文件拖入；二是支持GPU加速

**Comment by buxuku** [comment]
拖拽添加视频这个功能可以加上，GPU加速涉及到的资源文件非常庞大， 500多M，且手头没有 windows 真机，短期可能暂时加不上。
