### ISSUE TITLE
无法下载模型(window10版本)

### ISSUE THREAD

**Issue by jerrydeng01** [buxuku/video-subtitle-master#13]
Error: ENOENT: no such file or directory, open 'C:\Users\JYO\AppData\Roaming\video-subtitle-master\whisper.cpp\models\download-ggml-model.cmd'

**Comment by buxuku** [comment]
这个是因为 `whisper.cpp` 没有成功克隆下来，手动删除 `C:\Users\JYO\AppData\Roaming\video-subtitle-master\whisper.cpp` 这个目录，然后运行软件，重新安装一下 `whisper.cpp` 即可。

**Comment by Wang-Mer** [comment]
下载模型能不能添加一个进度条

**Comment by Wang-Mer** [comment]
还有就是每个模型是单独的一个文件夹吗

**Comment by Wang-Mer** [comment]
通知使用系统通知

**Comment by Wang-Mer** [comment]
下载好的模型还是提示需要下载

**Comment by buxuku** [comment]
> 下载好的模型还是提示需要下载

这个方便截个图吗？

**Comment by Wang-Mer** [comment]
![image](https://github.com/buxuku/video-subtitle-master/assets/56023866/6bbf63e2-18d8-4267-804d-104fd19ce6d7)
![image](https://github.com/buxuku/video-subtitle-master/assets/56023866/21462c56-52b7-4027-938d-2927a93c2a90)

**Comment by Wang-Mer** [comment]
![Uploading image.png…]()

**Comment by Wang-Mer** [comment]
![image](https://github.com/buxuku/video-subtitle-master/assets/56023866/8acb7a43-4aa1-4e1f-b667-906ba0b584f6)

**Comment by buxuku** [comment]
目前已经发布 1.0.14 版本，增加了模型下载进度（仅支持Mac），以及 whisper 安装的成功率，可以尝试该版本是否能够成功下载。

**Comment by Wang-Mer** [comment]
> 目前已经发布 1.0.14 版本，增加了模型下载进度（仅支持Mac），以及 whisper 安装的成功率，可以尝试该版本是否能够成功下载。

![image](https://github.com/buxuku/video-subtitle-master/assets/56023866/92e93f73-4197-42b7-9323-8374833b7ef3)
![image](https://github.com/buxuku/video-subtitle-master/assets/56023866/65f0e23d-63a0-49dc-a2da-6ab802c0862a)

**Comment by Wang-Mer** [comment]
> 目前已经发布 1.0.14 版本，增加了模型下载进度（仅支持Mac），以及 whisper 安装的成功率，可以尝试该版本是否能够成功下载。

这个模型文件夹好混乱，

**Comment by buxuku** [comment]
> > 目前已经发布 1.0.14 版本，增加了模型下载进度（仅支持Mac），以及 whisper 安装的成功率，可以尝试该版本是否能够成功下载。
> 
> 这个模型文件夹好混乱，

这个 `whisper.cpp` 官方项目的文件。 参见 https://github.com/ggerganov/whisper.cpp/tree/master/models

**Comment by Wang-Mer** [comment]
> > > 目前已经发布 1.0.14 版本，增加了模型下载进度（仅支持Mac），以及 whisper 安装的成功率，可以尝试该版本是否能够成功下载。
> 
> > 
> 
> > 这个模型文件夹好混乱，
> 
> 
> 
> 这个 `whisper.cpp` 官方项目的文件。 参见 https://github.com/ggerganov/whisper.cpp/tree/master/models

好的

**Comment by js79903** [comment]
如果从video-subtitle-master中下载不了,请问能从其它地方手动下载然后放在指定的夹中吗?

**Comment by js79903** [comment]
我单独下载ggml-medium.bin模型到指定夹了,C:\Users\tb\AppData\Roaming\video-subtitle-master\whisper.cpp\models\,会报错,请问有办法解决吗?
![image](https://github.com/buxuku/video-subtitle-master/assets/5943499/3a64dc3a-3277-4180-a5f7-e1ed09d0dd2f)

**Comment by asa-world** [comment]
> whisper.cpp

我也是，请问你解决了吗

**Comment by prometheus-alien** [comment]
无法下载+1，重装删除也不行

**Comment by PandaMcr** [comment]
![无法下载任何模型](https://github.com/user-attachments/assets/47435a8d-6568-49cd-8e8f-4f9a2a03d554)
这个应该怎么办？无法下载任何模型，windows10操作系统

**Comment by walirt** [comment]
还是下载不了

**Comment by walirt** [comment]
手动下载了
