### ISSUE TITLE
win电脑 软件版本1.0.18无法下载模型

### ISSUE THREAD

**Issue by arcfang** [buxuku/video-subtitle-master#35]
![屏幕截图 2024-09-25 001636](https://github.com/user-attachments/assets/82c03b83-bb5f-4c22-aa1b-b33324c0adca)

**Comment by uhayate** [comment]
故障+1，在软件的界面内下载模型，可以观察到数据流量在走，但是下载完后，软件没有任何变化，也不知道文件下到哪儿了，也不载入

**Comment by uhayate** [comment]
好像是下载地址的域名出问题了，望修复

**Comment by uhayate** [comment]
好像可以解决了。
https://huggingface.co/ggerganov/whisper.cpp/tree/main
去这里自己手动下载好model后放进文件夹里就OK

**Comment by martjay** [comment]
> 好像可以解决了。 https://huggingface.co/ggerganov/whisper.cpp/tree/main 去这里自己手动下载好model后放进文件夹里就OK

放哪个文件夹啊

**Comment by uhayate** [comment]
> > 好像可以解决了。 https://huggingface.co/ggerganov/whisper.cpp/tree/main 去这里自己手动下载好model后放进文件夹里就OK
> 
> 放哪个文件夹啊

放哪儿不重要了，玩具项目。
换：https://github.com/Chenyme/Chenyme-AAVT

**Comment by buxuku** [comment]
最新版本可以手动导入模型
