### ISSUE TITLE
下载的模型存放在什么位置

### ISSUE THREAD

**Issue by GaoHaHa-IronMan** [buxuku/video-subtitle-master#4]

**Comment by buxuku** [comment]
`/Users/xxx/Library/Application Support/video-subtitle-master/whisper.cpp/models`  在这个目录里面，其中 `xxx` 你的电脑当前的用户名
接下来我也将做一个模型管理的功能，可以下载，删除模型文件。

**Comment by midpoint** [comment]
在windows环境中，模型放在这里：
C:\Users\你的用户目\AppData\Roaming\video-subtitle-master\whisper.cpp\models\
