### ISSUE TITLE
deeplx

### ISSUE THREAD

**Issue by chinarui-na** [buxuku/video-subtitle-master#45]
没看到在哪启动的deeplx进程，进而支持访问本地1188端口

**Comment by buxuku** [comment]
deeplx 非内置的服务，请参考 https://github.com/OwO-Network/DeepLX?tab=readme-ov-file 先在本地运行起该服务

**Comment by Durden-T** [comment]
可以支持自定义endpoint吗？比如https://deeplx.xxx.com/translate?key=xxx

**Comment by buxuku** [comment]
v1.3.0 版本已经支持，可以在输入 key 的地方输入 endpoint
