### ISSUE TITLE
Error: spawn Unknown system error -86: ffmpeg 转码出错！

### ISSUE THREAD

**Issue by xujiahai** [buxuku/video-subtitle-master#5]

**Comment by buxuku** [comment]
请问你的运行环境是？转码的视频格式是？

**Comment by xujiahai** [comment]
MacBook pro 2015 15寸的 系统版本是12.7.5，下载后没有设置，视频是一个MP4 1080P的
<img width="307" alt="c0955133344ae08f57a656548ab1d1d" src="https://github.com/buxuku/video-subtitle-master/assets/8489644/f95ebf75-d150-4690-a14d-c786f7f34f22">

**Comment by jiji262** [comment]
碰到一样的问题，所有的mp4都不行，都是这个错误提示。
